gallery/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="gallery"),
    path("<int:image_id>", views.image, name="image"),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("index", views.index, name="index"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("login", views.login, name="login"),
    path("projects", views.projects, name="projects"),
    path("projects/<project>", views.projects, name="projects"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pages.urls")),
    path("admin/", admin.site.urls),
    path("gallery/", include("gallery.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models
from django.utils import timezone


class GalleryItems(models.Model):
    image = models.ImageField(upload_to="photos")
    description = models.CharField(max_length=300)
    title = models.CharField(max_length=100, default="Image")
    date = models.DateTimeField(default=timezone.now, blank=True)
    is_published = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Gallery Items"

    def __str__(self):
        return self.title

pages/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from random import choice
import logging

log = logging.getLogger(__name__)


class About(models.Model):
    content = RichTextField()

    class Meta:
        verbose_name = "About Form"

    def __str__(self):
        return "About entry"


class ContactForm(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()
    viewed = models.BooleanField(default=False)
    contact_date = models.DateTimeField(default=timezone.now, blank=True)

    class Meta:
        verbose_name = "Contact Form"
        verbose_name_plural = "Contact Forms"

    def __str__(self):
        return self.name


class Skills(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100, blank=True)
    percentage = models.PositiveSmallIntegerField()
    is_published = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Skill"
        verbose_name_plural = "Skills"

    def __str__(self):
        return self.name

    @classmethod
    def get_all(cls):
        try:
            return cls.objects.all()
        except Exception as e:
            log.error("Cannot retrieve Skills from database due to error: ", e)


class Projects(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    address = models.URLField()
    is_published = models.BooleanField(default=False)
    date = models.DateField(auto_now=True)

    class Meta:
        verbose_name = "Project"
        verbose_name_plural = "Projects"

    def __str__(self):
        return self.title

    @classmethod
    def get_all(cls):
        try:
            return cls.objects.filter(is_published=True)
        except Exception as e:
            log.error("Cannot retrieve Projects from database due to error: ", e)


class Quotes(models.Model):
    title = models.CharField(max_length=200)
    text = models.CharField(max_length=1000)
    source = models.CharField(max_length=5)
    bg_photo = models.ImageField(upload_to="images/%Y/%m/%d/")

    class Meta:
        verbose_name = "Quote"
        verbose_name_plural = "Quotes"

    def __str__(self):
        return self.title

    @classmethod
    def get_random_quote(cls):
        try:
            all_quotes = cls.objects.values_list("id", flat=True)
            random_quote = choice(all_quotes)
            quote = cls.objects.get(id=random_quote)
            return quote
        except Exception as e:
            log.error("Cannot retrieve Quotes from database due to error: ", e)

gallery/forms.py
from django import forms
from .models import GalleryItems


class GalleryForm(forms.ModelForm):
    class Meta:
        model = GalleryItems
        fields = ("title", "description", "image")

gallery/views.py
from django.shortcuts import render, redirect
from gallery.models import GalleryItems
from gallery.forms import GalleryForm
from gallery.utils import chunks


def index(request):
    if request.method == "POST":
        form = GalleryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("gallery")
    else:
        images_all = list(GalleryItems.objects.all().filter(is_published=True))
        images = list(chunks(images_all, 4))

        form = GalleryForm()
        return render(
            request,
            "pages/gallery.html",
            {
                "images_col1": images[0],
                "images_col2": images[1],
                "images_col3": images[2],
                "images_col4": images[3],
                "image": None,
                "form": form,
            },
        )


def image(request, image_id: int):
    image = GalleryItems.objects.get(pk=image_id)
    return render(request, "pages/gallery.html", {"image": image})

pages/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import messages, auth
from pages.models import About, ContactForm, Skills, Projects, Quotes
from pages.todays_info import TodaysInfo
from pages.tasks import send_email_task
from pages.weather import WeatherAPI


import logging

log = logging.getLogger(__name__)


def index(request):
    if request.method == "GET":

        # get all skills
        skills = Skills().get_all()

        # get quotes
        quote = Quotes().get_random_quote()

        # get today's inf
        todays_info = TodaysInfo().get_events()

        # get today's weather
        weather = WeatherAPI().get()

        # get list of projects
        projects_list = Projects().get_all()

        return render(
            request,
            "pages/index.html",
            {
                "skills": skills,
                "quote": quote,
                "projects": projects_list,
                "todays_event": todays_info["events"],
                "todays_deaths": todays_info["deaths"],
                "todays_births": todays_info["births"],
                "weather": weather,
            },
        )

    elif request.method == "POST":
        login(request)


def about(request):
    context = {"about": About.objects.first()}
    return render(request, "pages/about.html", context)


def contact(request):
    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]
        message = request.POST["message"]

        contact_form = ContactForm(name=name, email=email, message=message)
        contact_form.save()

        # celery task
        send_email_task(name, message)

        messages.success(request, "Your message has been send.")
        return render(request, "pages/contact.html")
    else:
        return render(request, "pages/contact.html")


def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect("admin")
        else:
            messages.error(request, "Invalid credentials.")
            return HttpResponseRedirect("login")
    else:
        return render(request, "pages/login.html")


def projects(request, project=None):
    if project == "compiler":
        return render(request, "pages/compiler.html")
    else:
        return HttpResponseRedirect("index")

templates/base.html
{% load static %}
<!--
	Author: W3layouts
	Author URL: http://w3layouts.com
	License: Creative Commons Attribution 3.0 Unported
	License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html lang="en">
<head>
<title>Home Page</title>

	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<meta name="keywords" content="" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--// Meta tag Keywords -->

	<!-- banner slider css -->
	<link href="{% static 'css/minimal-slider.css' %}" rel='stylesheet' type='text/css' />
	<!-- //banner slider css -->

	<!-- css files -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> <!-- Bootstrap-Core-CSS -->
    <link href="{% static 'css/style6.css' %}" rel='stylesheet' type='text/css' />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" /> <!-- Style-CSS -->
	<link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}"> <!-- Font-Awesome-Icons-CSS -->
	<!-- //css files -->

	<!--web font-->
	<link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=latin-ext" rel="stylesheet">
	<!--//web font-->

	<!--	Favicon-->
	<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
</head>

<body>
	<!-- Header -->
	{% include 'partials/_header.html' %}
	<!-- Block Content -->
	{% block content %}
	{% endblock %}

	<!--Footer-->
	{% include 'partials/_footer.html' %}

	<!-- Login section-->
	{% include 'partials/_login.html' %}

	<!-- Modals import-->
	{% include 'partials/_modals.html' %}

	<!-- js -->
	<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script> <!-- Necessary-JavaScript-File-For-Bootstrap -->
	<!-- //js -->

	<!-- search overlay -->
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- //search overlay -->

	<!--search jQuery-->
    <script src="{% static 'js/classie-search.js' %}"></script>
    <script src="{% static 'js/demo1-search.js' %}"></script>
    <!--//search jQuery-->

    <!-- dropdown nav -->
    <script>
        $(document).ready(function() {
            $(".dropdown").hover(
                function() {
                    $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                    $(this).toggleClass('open');
                },
                function() {
                    $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                    $(this).toggleClass('open');
                }
            );
        });
    </script>
    <!-- //dropdown nav -->

	<!-- banner slider js -->
	<script src="{% static 'js/minimal-slider.js' %}"></script>
	<!-- //banner slider js -->

	<!-- Stats-Number-Scroller-Animation-JavaScript -->
	<script src="{% static 'js/waypoints.min.js' %}"></script>
	<script src="{% static 'js/counterup.min.js' %}"></script>
	<script>
		jQuery(document).ready(function( $ ) {
			$('.counter').counterUp({
				delay: 100,
				time: 1000
			});
		});
	</script>
	<!-- //Stats-Number-Scroller-Animation-JavaScript -->

	<!-- start-smoth-scrolling -->
	<script src="{% static 'js/SmoothScroll.min.js' %}"></script>
	<script src="{% static 'js/move-top.js' %}"></script>
	<script src="{% static 'js/easing.js' %}"></script>
	<script>
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
	<!-- here stars scrolling icon -->
	<script>
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

			});
	</script>
	<!-- //here ends scrolling icon -->
	<!-- start-smoth-scrolling -->

	<!-- custom script -->
	<script src="{% static 'js/main.js' %}"></script>
<!--	<script src="{% static 'js/gallery.js' %}"></script>-->
</body>
</html>

templates/pages/about.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- inner page banner -->
<section class="inner-page-banner">
	<div class="page-heading text-center">
		<h2>About Page</h2>
		<span class="section_1-breadcrumbs"><a href="{% url 'index' %}">
			<i class="fa fa-home home_1"></i> Home</a> <span>/ <a href="{% url 'about' %}"> About page</a></span></span>
	</div>
</section>
<!-- //inner page banner -->

<!-- welcome -->
<section class="Welcome py-5">
	<div class="container py-sm-3">
		<div class="heading pb-4">
			<h3 class="heading mb-2 text-center"> <span>About </span> Me </h3>
			<p class="para mb-5 text-center">My short story</p>
		</div>
		<div class="welcome-grids row">
			<div class="col-lg-6 mb-lg-0 mb-5">
				{{ about.content | safe }}
			</div>
			<div class="col-lg-3 col-md-4 col-6 pr-1 welcome-image">
				<img src="{% static 'images/a1.jpg' %}" class="img-fluid" style="width: 270px; height: 380px;" alt="Shire" /><br><br>
				<img src="{% static 'images/c1.jpg' %}" class="img-fluid" style="width: 270px; height: 380px;" alt="Shire" />
			</div>
			<div class="col-lg-3 col-md-4 col-6 pl-1 welcome-image">
				<img src="{% static 'images/a2.jpg' %}" class="img-fluid" style="width: 270px; height: 380px;" alt="Queenstown" /><br><br>
				<img src="{% static 'images/c2.jpg' %}" class="img-fluid" style="width: 270px; height: 380px;" alt="Queenstown" />
			</div>

		</div>
	</div>
</section>
<!-- welcome -->

{% endblock %}

templates/pages/compiler.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<!-- inner page banner -->
<section class="inner-page-banner">
	<div class="page-heading text-center">
		<h2>About Page</h2>
		<span class="section_1-breadcrumbs"><a href="{% url 'index' %}">
			<i class="fa fa-home home_1"></i> Home</a> <span>/ <a href="{% url 'projects' 'compiler' %}"> Excel Compiler</a></span></span>
	</div>
</section>
<!-- //inner page banner -->

<!-- welcome -->
<section class="Welcome py-5">
	<div class="container py-sm-3">
		<div class="heading pb-4">
			<h3 class="heading mb-2 text-center"> <span>About </span> Project </h3>
			<p class="para mb-5 text-center">Excel Compiler</p>
		</div>

		<div class="welcome-grids row">
			<div class="mb-lg-0 mb-5">
				<h3 class="mt-lg-4">At the beginning</h3>
				<p class="my-4">One of processes in my work required from person doing it to download some data files,
				restructurize them, search for certain values, cross-check etc. This part sometimes took up to 4-5 hours.
				And then everything was checking in validation system in other tool as a next step in this process.</p>
				<p class="my-4">If everything was done correctly at first time, entire task for this process took up to 6 hours.
				But there was a problem. Everytime.</p>
				<p class="my-4">Normally this took up to 12 hours. Not great, not terrible. Nope, very terrible. Nightmare.</p>
				<p class="my-4">I decided to solve it somehow.</p>
			</div>
			<div class="mb-lg-0 mb-5">
				<h3 class="mt-lg-4">How it works</h3>
				<p class="my-4">It is semi-automated process, due to closed API of other tools. However, script shorten
					time of entire task from about 12 hours to just 1 hour, where running app took up to 1.5 second to prepare
					required documents.</p>
				<p class="my-4">This step starts with data preparation. User has to download needed files manually and
					save it in certain directory. Let's say, we can sum records from all the inputted files to 8 thousands.
				And run the app.</p>
				<p class="my-4">Secondly, user has to type with which asset he/she would like to work, and then type
					1 of 2 mode of data, he/she would like to receive.</p>
				<p class="my-4">After 1, up to 1.5 seconds, user has the output. The app in saving data in known structures,
				 rearrange them, searches for values, validate and cross-check. If some record is incorrect, user will know about it.
				Output file contains inputted data, some of the critical single steps and almost ready-to-use data.</p>
				<p class="my-4">Thirdly, output data has to be checked due to some incorrect data - normally it is limited
				to visual check of records.</p>
				<p class="my-4">Finally, user can user app to extract correct data from above files to receive ready-to-use
				spreadsheet required in external tool.</p>
				<p class="my-4">Application in written in Python with <a href="https://openpyxl.readthedocs.io/en/stable/">Openpyxl</a> library.
					Runs in console, but exported with <a href="https://www.pyinstaller.org/">PyInstaller</a> to exe file.
					Using a <a href="https://github.com/tartley/colorama">Colorama</a> and <a href="https://pypi.org/project/termcolor/">Termcolor</a>
					for output. Due to internal restrictions I cannot show any piece of application.</p>
			</div>
		</div>

	</div>
</section>
<!-- welcome -->

{% endblock %}

templates/pages/contact.html
{% extends "base.html" %}
{% block content %}

<!-- inner page banner -->
<section class="inner-page-banner">
	<div class="page-heading text-center">
		<h2>Contact Page</h2>
		<span class="section_1-breadcrumbs"><a href="{% url 'index' %}">
			<i class="fa fa-home home_1"></i> Home</a> <span>/ <a href="{% url 'contact' %}"> Contact</a></span></span>
	</div>
</section>
<!-- //inner page banner -->

<!-- contact -->
<section class="contact py-5">
	<div class="container">
		<div class="heading pb-4">
			<h3 class="heading mb-2 text-center"> <span>Contact </span> Me </h3>
			<p class="para mb-5 text-center">In emergency of anything (except spam and low quality jokes), do not hesitate to contact me.</p>
		</div>
		<div class="row contact-agileinfo m-5 form-group row align-items-center justify-content-center">
			{% include 'partials/_alerts.html' %}
			<div class="contact-right text-center">
				<form action="{% url 'contact' %}" method="POST">
					{% csrf_token %}
					<input type="text" name="name" placeholder="Name" required="">
					<input type="email" class="email" name="email" placeholder="Email" required="">
					<textarea name="message" placeholder="Message" required=""></textarea>
					<button type="submit" class="btn btn-primary submit mb-4">Submit</button>
				</form>
			</div>

		</div>
	</div>
</section>
{% endblock %}

templates/pages/gallery.html
{% extends "base.html" %}

{% block content %}

<!-- inner page banner -->
<section class="inner-page-banner" xmlns="http://www.w3.org/1999/html">
	<div class="page-heading text-center">
		<h2>Gallery Page</h2>
		<span class="section_1-breadcrumbs"><a href="{% url 'index' %}"><i class="fa fa-home home_1">
		</i> Home</a> <span>/ <a href="{% url 'gallery' %}"> Gallery</a></span></span>
	</div>
</section>
<!-- //inner page banner -->

<!--Style tag inside body tag is awful, I know, but it was only way for modals to work properly...-->
<style>
	.row {
  display: flex;
  flex-wrap: wrap;
  padding: 0 4px;
}

/* Create four equal columns that sits next to each other */
.column {
  flex: 25%;
  max-width: 25%;
  padding: 0 4px;
}

.column img {
  margin-top: 8px;
  vertical-align: middle;
  width: 100%;
}

/* Responsive layout - makes a two column-layout instead of four columns */
@media screen and (max-width: 800px) {
  .column {
    flex: 50%;
    max-width: 50%;
  }
}

/* Responsive layout - makes the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 600px) {
  .column {
    flex: 100%;
    max-width: 100%;
  }
}
</style>

<!-- Gallery -->
<section id="gallery">
	{% if not image %}
		<div class="row" style="margin: 10px 10px 10px 10px;">
			<div class="column">
				{% for image_col1 in images_col1 %}
					{% if image_col1.is_published %}
					<a href="{% url 'image' image_col1.pk %}">
						<img src="{{ image_col1.image.url }}" alt="{{ image_col.title }}" class="myImg">
					</a>
					{% endif %}
				{% endfor %}
			</div>
			<div class="column">
				{% for image_col2 in images_col2 %}
					{% if image_col2.is_published %}
					<a href="{% url 'image' image_col2.pk %}">
						<img src="{{ image_col2.image.url }}" alt="{{ image_col.title }}" class="myImg">
					</a>
					{% endif %}
				{% endfor %}
			</div>
			<div class="column">
				{% for image_col3 in images_col3 %}
					{% if image_col3.is_published %}
					<a href="{% url 'image' image_col3.pk %}">
						<img src="{{ image_col3.image.url }}" alt="{{ image_col.title }}" class="myImg">
					</a>
					{% endif %}
				{% endfor %}
			</div>
			<div class="column">
				{% for image_col4 in images_col4 %}
					{% if image_col4.is_published %}
					<a href="{% url 'image' image_col4.pk %}">
						<img src="{{ image_col4.image.url }}" alt="{{ image_col.title }}" class="myImg">
					</a>
					{% endif %}
				{% endfor %}
			</div>
		</div>

		{% if user.is_authenticated %}
			<div class="m-5 form-group row align-items-center justify-content-center">
				<div class="border p-5">
					<div class="col-xs-3">
						<form method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							<div id="div_id_title" class="form-group">
								<label for="id_title" class="col-form-label  requiredField">Title<span class="asteriskField">*</span> </label>
								<div class="">
									<input type="text" name="title" placeholder="Image Title" maxlength="100" class="textinput textInput form-control" required id="id_title">
								</div>
							</div>
							<div id="div_id_description" class="form-group">
								<label for="id_description" class="col-form-label  requiredField">Description<span class="asteriskField">*</span></label>
								<div class="">
									<input type="text" name="description" placeholder="Image Description" maxlength="300" class="textinput textInput form-control" required id="id_description">
								</div>
							</div>
							<div id="div_id_image" class="form-group">
								<label for="id_image" class="col-form-label  requiredField">Image<span class="asteriskField">*</span></label>
								<div class="">
									<input type="file" name="image" accept="image/*" class="clearablefileinput" required id="id_image">
								</div>
							</div>

							<button type="submit" class="btn btn-success">Upload</button>
						</form>
					</div>
				</div>
			</div>
		{% endif %}
	{% elif image %}
		<div class="mx-auto m-3">
				<h3 class="heading mb-2 text-center"> {{ image.title }} </h3>
				<img src="{{ image.image.url }}" alt="{{ image.title }}" class="rounded mx-auto d-block" style="max-width: 800px;">
				<p class="text-center"><span>Description:</span> {{ image.description }}</p>
		</div>
	{% else %}
	<p>Nothing to show.</p>
	{% endif %}
</section>
{% endblock %}

templates/pages/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}

{% include 'partials/_frontpage_slides.html' %}

<!-- welcome -->
<section class="Welcome py-5">
	<div class="container py-sm-5">
		<div class="welcome-grids row">
			<div class="col-lg-6 mb-lg-0 mb-5">
				<h3 class="heading mb-2 text-center"> <span>About </span> Portfolio </h3>
				<p class="my-4">Welcome in my portfolio website.</p>
				<p class="mb-4">Firstly it was created to learn Django framework, however,
					it turns out it is perfect place to present other my projects. Take a look around and have fun.</p>
				<p class="mb-4">This page is build in <a href="https://www.djangoproject.com/" target="_blank">Django framework</a>
					with <a href="https://www.postgresql.org/" target="_blank">PostgreSQL</a> database.
					All together put into <a href="https://www.docker.com/" target="_blank">Docker</a>.</p>
				<p class="mb-4">Still in construction :)</p>
			</div>
			<div class="col-lg-3 col-md-4 col-6 pr-1 welcome-image">
				<img src="{% static 'images/a1.jpg' %}" class="img-fluid" alt="" />
			</div>
			<div class="col-lg-3 col-md-4 col-6 pl-1 welcome-image">
				<img src="{% static 'images/a2.jpg' %}" class="img-fluid" alt="" />
			</div>
		</div>
	</div>
</section>
<!--welcome-->

<!-- Skills -->
<section class="bottom-last">
	<div class="bottom-bg py-5 bs-slider-overlay text-left">
		<div class="container py-md-5">
			<div class="heading pb-4">
				<h3 class="heading mb-2 text-center text-white"> <span style="color: #ff0000;">My </span> Skills </h3>
				<p class="para mb-5 text-center">I am self-taught in python, motivated for new.</p>
			</div>
			<div class="row grids">
				<div class="col-lg-6">
					<h4 class="title">Professional Skills</h4>
				</div>
				<div class="col-md-6 mt-lg-0 mt-5">
					{% for skill in skills %}
						{% if skill.is_published %}
							<div class="progress-one my-4">
								<h4 class="progress-tittle">{{ skill.name }}</h4>
								<div class="progress">
									<div class="progress-bar progress-bar-striped {{ skill.color }} " role="progressbar" style="width: {{ skill.percentage }}%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
								</div>
							</div>
						{% endif %}
					{% endfor %}
                </div>
			</div>
		</div>
	</div>
</section>
<!-- //Skills -->

<!-- Projects -->
<section class="features py-5" id="projects">
	{% if projects %}
	<div class="container py-sm-5">
		<div class="heading pb-4">
			<h3 class="heading mb-2 text-center"> <span>My </span> Projects </h3>
			<p class="para mb-5 text-center">Stay awhile and check out my works</p>
		</div>
		<div class="feature-grids row">
			{% for project in projects %}
				{% if project.is_published %}
					<div class="col-lg-4 col-md-6">
						<a href="{{ project.address }}">
						<div class="f1 p-sm-5 p-4">
							<i class="fas fa-arrow-right" aria-hidden="true"></i>
							<h3 class="my-3">{{ project.title}}</h3>
							<p>{{ project.description }}</p>
						</div>
						</a>
					</div>
				{% endif %}
			{% endfor %}
		</div>
	</div>
	{% endif %}
</section>
<!-- //Projects -->

{% endblock %}

templates/pages/login.html
{% extends 'base.html' %}

{% block content %}

<!-- inner page banner -->
<section class="inner-page-banner">
	<div class="page-heading text-center">
		<h2>Login Page</h2>
		<span class="section_1-breadcrumbs"><a href="{% url 'index' %}">
			<i class="fa fa-home home_1"></i> Home</a> <span>/ <a href="{% url 'login' %}"> Login</a></span>
        </span>
	</div>
</section>
<!-- //inner page banner -->
<div class="container py-5 ">
    <h5 class="text-center mb-4">Login Now</h5>
    <div class="p-5 m-5 form-group  align-items-center justify-content-center border">
        {% include 'partials/_alerts.html' %}
        <form id="login-form" action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label class="mb-2">Username</label>
                <input type="text" class="form-control" id="id_username" name="username" placeholder="Username" required="">
            </div>
            <div class="form-group">
                <label class="mb-2">Password</label>
                <input type="password" class="form-control" id="id_password" name="password" placeholder="Password" required="">
            </div>
            <div class="form-check mb-2">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary submit mb-4">Sign In</button>
        </form>
    </div>
</div>
{% endblock %}

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            <strong>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Error:
                {% else %}
                    {{ message.tags | title }}
                {% endif %}
            </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}